name: Lints

on: [push, pull_request]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.63.0
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: ${{ matrix.rust }}
            components: rustfmt, clippy
            override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
